const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Our Breakfast Special - a very light & fluffy pancake with fresh buttermilk, which will give you enough energy for the entire day.`,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Two ¼ pound patties on a potato roll with house pickles, spinach, tomatoes, American cheese, onion, and special sauce.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `A perfect milkshake filled with crushed oreos, doughnut & cookies, full of sweetness & love.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `A fulfilling breakfast option full of protein & good carbs enough to make a wholesome meal. A must try!`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `A burger filled with two slices of cheese, beef patty, a lot of egg protein and our special sauce.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Filled with 3 scoops cookies'n cream icecream, 1 handful crushed Oreos, 3 spoonfuls cream cheese with splash of milk.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Four patties, four slices of cheese, a heaping pile of bacon and our secret sauce make it our best-selling burger.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Three beef patties, one slice of cheese, lettuce, tomato, onions with a serving of fries & onion rings - making it a perfect guilty pleasure.`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `With 3 scoops strawberry ice cream, a handful of chopped pound cake, banana & splash of milk - a perfect milkshake to share with your Quarantine Buddy!`,
  },
]
export default menu
